# Generated by Django 3.1.1 on 2020-09-04 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('username', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=32, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
