# Generated by Django 3.0.3 on 2020-09-06 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200904_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
