# Generated by Django 3.0.3 on 2020-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20200906_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
